# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: rene
  password: enter

development:
  <<: *default
  database: 'trackitall_dev'

test:
  <<: *default
  database: 'trackitall_test'

# production will be overwritten by MINA
production:
  <<: *default
  database: 'trackitall_prod'